server:
  port: 8087

spring:
  application:
    name: smartomni-service-ai
  datasource:
    url: jdbc:postgresql://localhost:5432/smartomni
    username: smartomni
    password: smartomni
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

smartomni:
  ai-python-service:
    base-url: http://localhost:8000  # dia chi cua AI Microservice viet bang Python (repo rieng)

logging:
  level:
    com.smartomni: DEBUG
